version: '{build}'
image: Visual Studio 2017
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
build_script:
- ps: ./build.ps1
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: WHuWt/1Dvd2MYxY+EzjcL+RFD9f6GnQ0ZEiVHdtn/MpE7sHMcYqe6ENGvFDSuyJw
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
